<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Register</name>
   <tag></tag>
   <elementGuidId>67a74c07-a396-448f-aeab-921fad2a28ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#registerBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='registerBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce585ba5-adf4-4941-97bd-68452c309ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>registerBtn</value>
      <webElementGuid>3b8240f6-ac79-4900-a791-feeebf068193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e9c0f633-b864-4cc8-b18d-13c57f4596bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>af6fe773-1028-40da-aa07-a2922095546c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>registerAccount()</value>
      <webElementGuid>50cd630f-64b0-4886-b7cf-7341581cfe26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Register
          </value>
      <webElementGuid>7759725b-f81b-4baa-8ebe-0f178de470be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;registerBtn&quot;)</value>
      <webElementGuid>24fcdc94-cf05-4888-8492-1fa0c18ccdae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='registerBtn']</value>
      <webElementGuid>b03517a7-7acb-43f5-a0a4-29b0201edc23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/button</value>
      <webElementGuid>13cf16fd-d660-48ee-9233-4726ce5d90cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I agree with the terms and conditions'])[1]/following::button[1]</value>
      <webElementGuid>514c5b86-0c3f-4d4f-aa9e-d8df9b390da5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password *'])[1]/following::button[1]</value>
      <webElementGuid>44e449c4-6a97-4ed0-96df-87da40529b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'registerBtn', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>dff0171f-f569-4310-b6ac-e1dc98d08628</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/button</value>
      <webElementGuid>f5d84863-e22c-4f30-aed1-81da29c51850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'registerBtn' and @type = 'submit' and (text() = '
            Register
          ' or . = '
            Register
          ')]</value>
      <webElementGuid>60c0d790-e217-4b26-afa0-4a95a471a57b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
