<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Bad credentials Please try again Make s_5a4980</name>
   <tag></tag>
   <elementGuidId>6ea8a600-9690-4eab-9bc1-7d6cf7d8b4c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='message']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>59812705-b14f-4fe2-b776-f7401abfa7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alert alert-danger</value>
      <webElementGuid>80c32a5e-a1c2-4c24-820f-885a948fae84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>alert</value>
      <webElementGuid>170b6ad9-130f-421e-918b-da492570f544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>e4e48332-2585-4dd4-bbc5-93eeb88872f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bad credentials! Please try again! Make sure that you've registered.</value>
      <webElementGuid>ba21f73d-a4f3-43ff-9022-a93976f0d3ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;message&quot;)</value>
      <webElementGuid>5818eb01-8ac4-490b-ad4e-a0972d20fbf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='message']</value>
      <webElementGuid>7f6bf293-c0dc-493c-a01d-f2ea39695245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div</value>
      <webElementGuid>be194a86-de41-46c6-a0ce-71dd60d528dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::div[1]</value>
      <webElementGuid>87995cd7-f521-432d-affb-b893ce673897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::div[1]</value>
      <webElementGuid>c172d57b-400f-4d06-82cd-f1fbf3bbc2a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'message', '&quot;', ')')])[1]/preceding::div[1]</value>
      <webElementGuid>ec0deaef-5462-4017-86b0-9e02a17e7534</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>76b9f965-b990-4eea-a03b-273e1cf1db0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'message' and (text() = concat(&quot;Bad credentials! Please try again! Make sure that you&quot; , &quot;'&quot; , &quot;ve registered.&quot;) or . = concat(&quot;Bad credentials! Please try again! Make sure that you&quot; , &quot;'&quot; , &quot;ve registered.&quot;))]</value>
      <webElementGuid>2961c62d-a83a-40fe-bac1-a65fc6a01a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
