<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Range Date Picker Example_daterange</name>
   <tag></tag>
   <elementGuidId>1d355535-16db-4338-9704-5eb7824c7957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#range-date-calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='range-date-calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a3590169-a138-491f-b08f-b74bd4f2e3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>range-date-calendar</value>
      <webElementGuid>1f5c236b-c217-4701-b581-556a1242b831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebbe946a-0d26-4286-b8a0-20f81446b52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>582c8933-1a76-4dec-930f-64c9a6b28baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>daterange</value>
      <webElementGuid>6da9e897-0838-473c-9795-8ca1d82b5e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>01/01/2018 - 01/15/2018</value>
      <webElementGuid>cdcc4199-5caa-4292-b290-1263850f0413</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;range-date-calendar&quot;)</value>
      <webElementGuid>2df4b489-9274-404e-a8a6-16817891b60d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='range-date-calendar']</value>
      <webElementGuid>ecffeb9c-f454-491f-b075-58ae0672f9fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/input</value>
      <webElementGuid>6f0e3393-0f3e-4e5c-9dac-e97d4760913c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>21a8bcaf-f369-4823-b5c2-7e8e8edfd9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'range-date-calendar' and @type = 'text' and @name = 'daterange']</value>
      <webElementGuid>8131e8f1-d9f3-4bba-9d2e-bc2bef4fd371</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
