<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Basic Date Picker Example_calendar</name>
   <tag></tag>
   <elementGuidId>a2f5afde-b94a-4bb7-8a58-1a899705e7b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#calendar</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='calendar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>50e1ecb0-e472-4955-bfe7-ddf262ddb9ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>calendar</value>
      <webElementGuid>44035f67-5674-477e-bce8-10088b896a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>da1be28e-a18c-43f1-8ac8-865464302d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>251a31af-c710-4f88-b7df-d480bab3573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Pick a date</value>
      <webElementGuid>e396dbd1-062d-4130-af23-2968788b657c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;calendar&quot;)</value>
      <webElementGuid>60a85696-8690-4e8d-a829-ccda2c1bb85d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='calendar']</value>
      <webElementGuid>0dd2da08-6546-4ccf-9d70-99e20648197f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/input</value>
      <webElementGuid>65afeb1d-9b1a-43b3-874b-f3f0abad7832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>91427f39-26ea-4f0a-9857-2f5710999da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'calendar' and @type = 'text' and @placeholder = 'Pick a date']</value>
      <webElementGuid>16cf8210-fa2a-4fae-a7af-b9f8d236ff5a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
