<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_exampleCheck1</name>
   <tag></tag>
   <elementGuidId>7c601eb0-0f0c-4b27-879f-d732c8e1ffe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#exampleCheck1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='exampleCheck1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a68fd5ed-1a7c-4d00-844d-b9d12040f263</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6cf23a53-e2ea-43db-9f4e-a0f85095dead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d795ff92-1036-4e41-b700-eeab97cb6847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>exampleCheck1</value>
      <webElementGuid>8fbd29ea-4230-4e57-af61-e5381a0c4eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;exampleCheck1&quot;)</value>
      <webElementGuid>0e889b0d-1662-4976-914a-2cad20c43a11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='exampleCheck1']</value>
      <webElementGuid>a0aace74-e463-4c0b-8311-4da15a04c529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='registerForm']/div[7]/input</value>
      <webElementGuid>369a9b2d-73e2-476b-8312-1c0a1264dd5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>fefc30fe-52ef-4a42-b538-71cb6bee6bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'exampleCheck1']</value>
      <webElementGuid>84fe9a56-6ed4-454e-b12f-424f3a25eba7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
