<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clear the text_clearMe</name>
   <tag></tag>
   <elementGuidId>f53cd956-ab6a-450e-97ef-398c5d776716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#clearMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='clearMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78ea37e3-a846-4ec7-afb3-2ad140144b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>clearMe</value>
      <webElementGuid>563d48e5-8961-4014-9a7e-491ca7af3db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Koushik Chatterjee</value>
      <webElementGuid>2495b5c7-514e-440f-a21c-da9849a4f96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>31a5abac-2fa5-41d0-a3ed-7c860c8e48fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>dfb4e75d-17e2-4d66-b023-1d0d8e680069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a6c56e1e-7a9e-4203-b8c5-0a212e859493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;clearMe&quot;)</value>
      <webElementGuid>fdd71675-dde6-4ea9-ae6f-3c63d72f95f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='clearMe']</value>
      <webElementGuid>ebaba6f2-6dea-41f9-b6fd-458141d976c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>2bba82ce-cb7a-4410-acb8-1760a1eb6249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'clearMe' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>87aee1d5-ed64-47ac-a6c7-2650e2e540f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
