<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_What is inside the text box_getMe</name>
   <tag></tag>
   <elementGuidId>eb7b0421-06bf-4af9-a605-e894fee39716</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getMe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='getMe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0080063d-8757-4fe0-a44a-0b82f36b9675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getMe</value>
      <webElementGuid>574456ec-7d67-4508-a298-98f56fd6f7f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ortonikc</value>
      <webElementGuid>2d8618ec-0243-40b0-a9ac-da9769c8a574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>85c972a2-191f-44d7-ae9c-cd024f146bfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>c9b30c67-605e-4959-923a-138e21f9f357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54ffc3c7-066d-41b0-bebd-9b33e247d27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getMe&quot;)</value>
      <webElementGuid>6559891c-67cf-4f25-b3ef-f77f2a809a03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='getMe']</value>
      <webElementGuid>72e50c3b-c7ec-4ba6-936d-b7225be7613a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>60c946c0-0d23-4065-a73a-c80eda3455a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'getMe' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>9a4d7756-88cf-4503-a617-606bea884cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
