<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Append a text and press keyboard tab_join</name>
   <tag></tag>
   <elementGuidId>720b5047-4b3b-43b7-a43f-200f3ed52ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#join</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='join']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56732b89-7a67-47d7-9fdb-ed6253247bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>join</value>
      <webElementGuid>f3b8f618-feaa-4bc8-a652-02862e6ee5a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>I am good</value>
      <webElementGuid>5c51b870-ba12-414f-ae3a-b392cc146c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4b6b9057-2fd0-4fae-932b-b7f17f984f0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter </value>
      <webElementGuid>40216075-1e3b-4af3-baf0-6d9a290b44a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82627f8c-c146-45e5-9d44-c93645192683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;join&quot;)</value>
      <webElementGuid>1a870796-0b61-4eda-8421-28b9329ea15e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='join']</value>
      <webElementGuid>a44f0a90-eb5b-4672-9b7f-6b01e4f7ab6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>250f5bee-cdcd-4c8a-85ae-d95a0ca81fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'join' and @type = 'text' and @placeholder = 'Enter ']</value>
      <webElementGuid>34234faf-134c-4afc-ae45-07a78ccb2f4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
