<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm edit field is disabled_noEdit</name>
   <tag></tag>
   <elementGuidId>3c1e179e-1066-47f7-8899-bfe4cc418cad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#noEdit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='noEdit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b00e0e88-74ce-48b4-8e49-1e356977b87d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>noEdit</value>
      <webElementGuid>3a77d4d6-2eba-4c3b-bd27-30192052241e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f916fbec-7684-4dbc-8d6a-632bcde6536d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter</value>
      <webElementGuid>7756865b-2f98-4d95-8f05-9ae8f42c3cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5e4b29e2-d9bb-4e57-96db-42d1e2610ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;noEdit&quot;)</value>
      <webElementGuid>74f969fc-ff3d-4888-8008-672235c06da4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='noEdit']</value>
      <webElementGuid>2be469c0-f50a-4cae-9c5e-a79329ae228c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>80cf247a-a94a-449a-981d-4f5f1651c35c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'noEdit' and @type = 'text' and @placeholder = 'Enter']</value>
      <webElementGuid>00cab330-9131-4bdd-8f3e-623e523e6e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
