<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Confirm text is readonly_dontwrite</name>
   <tag></tag>
   <elementGuidId>353ecc5a-cbb1-4c31-8199-b017f7e9bb3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dontwrite</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='dontwrite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc8f94a3-c629-4b0d-96c5-c247d52e2ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dontwrite</value>
      <webElementGuid>12c84247-49c5-45ee-8007-6f1c96e44285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>206307d5-cdf8-4b14-bd09-884481ab93ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>This text is readonly</value>
      <webElementGuid>f6be63cf-9522-4c67-b909-ec5a0ac1efe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f961e8f5-4574-43cd-84a5-fdb548a3ad80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dontwrite&quot;)</value>
      <webElementGuid>d2b8792e-c0d8-405d-bd76-6843325380ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='dontwrite']</value>
      <webElementGuid>40c90ab2-d764-447c-afd6-9226d649f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/input</value>
      <webElementGuid>6c19e392-3358-4ffb-8340-963ad4b82118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'dontwrite' and @type = 'text']</value>
      <webElementGuid>d41282bb-92fb-4c62-b7e8-facf76bc69f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
